from .change_truck import ChangeTruckViewSet
from .checkin import CheckinViewSet
from .checkin_logic import CheckinLogic
from .commodity import CommodityViewSet
from .completed_journey import CompletedJourney
from .declaracion import DeclaracionViewSet
from .deduction import AddDeduction
from .ongoing_declaracion import OnGoingDeclaracionViewSet
from .payment_method import PaymentMethodViewSet
from .update_declaracion import UpdateDeclaracion
from .with_wieghted_bridge import CheckTheTruck
